#delimit;
qui{;

*cap rename name                 name                  ; cap label var name              "Name";
 cap rename nome                 name                  ; cap label var name			     "Name";
 cap rename ceivinc              cei                   ; cap label var cei               "Tax identifider for sole-propietorships";
*cap rename pis                  pis                   ; cap label var pis               "Worker identifier";
 cap rename cpf                  cpf                   ; cap label var cpf               "Natural person register (social security number)" ;
 cap rename num_pis              pis                   ; cap label var pis				 "Worker identifier";
 cap rename radiccnpj            cnpj_root             ; cap label var cnpj_root         "First 8 digits of CNPJ";
 cap rename numectps             ctps                  ; cap label var ctps				 "CTPS (employment record book)";
 cap rename ano                  year                  ; cap label var year              "Year";
 cap rename cepestab             zip                   ; cap label var zip               "Postal addressing code";
 cap rename dtnascimen           birth_date            ; cap label var birth_date        "Birth date";
 cap rename datadenascimento     birth_date            ; cap label var birth_date        "Birth date";
 cap rename genero               male                  ; cap label var male		 		 "=1 if male";
 cap rename idade                age                   ; cap label var age               "Age";
 cap rename faixaetari           age_group             ; cap label var age_group         "Age group";
 cap rename grinstruca           schooling             ; cap label var schooling 		 "Educational attainment";
 cap rename nacionalid           nationality           ; cap label var nationality       "Nationality";
 cap rename raca_cor             race                  ; cap label var race				 "Race";
 cap rename anochegbr            migration_year        ; cap label var migration_year    "Year of Arrival to Brazil";
 cap rename muntrab              muni_worker           ; cap label var muni_worker       "Municipality worker";
 cap rename portdefic            disabled              ; cap label var disabled			 "=1 if disabled";
 cap rename tpdefic              disability_type       ; cap label var disability_type   "Type of disability";
 cap rename empem3112            active                ; cap label var active            "=1 if employed as of 31/12";
 cap rename indalvara            judicial_permit       ; cap label var judicial_permit   "Worker with judicial permit";
 cap rename tempempr             tenure                ; cap label var tenure			 "Tenure in months";
 cap rename horascontr           hired_hours           ; cap label var hired_hours       "Weekly hours as in contract";
 cap rename tpvinculo            contract_type         ; cap label var contract_type     "Contract type";
 cap rename salcontr             hired_wage            ; cap label var hired_wage        "Contractual earnings";
 cap rename tiposal              earn_type       	   ; cap label var earn_type  	     "Earnings type";
 cap rename renda_1              earn_jan              ; cap label var earn_jan          "Average January earnings";
 cap rename renda_2              earn_feb              ; cap label var earn_feb          "Average February earnings";
 cap rename renda_3              earn_mar              ; cap label var earn_mar          "Average March earnings";
 cap rename renda_4              earn_apr              ; cap label var earn_apr          "Average April earnings";
 cap rename renda_5              earn_may              ; cap label var earn_may          "Average May earnings";
 cap rename renda_6              earn_jun              ; cap label var earn_jun          "Average June earnings";
 cap rename renda_7              earn_jul              ; cap label var earn_jul          "Average July earnings";
 cap rename renda_8              earn_aug              ; cap label var earn_aug          "Average August earnings";
 cap rename renda_9              earn_sep              ; cap label var earn_sep          "Average September earnings";
 cap rename renda_10             earn_oct              ; cap label var earn_oct          "Average October earnings";
 cap rename renda_11             earn_nov              ; cap label var earn_nov          "Average November earnings";
 cap rename renda_12             earn_dec              ; cap label var earn_dec          "Average December earnings";
 cap rename remjan               earn_jan              ; cap label var earn_jan          "Average January earnings";
 cap rename remfev               earn_feb              ; cap label var earn_feb          "Average February earnings";
 cap rename remmar               earn_mar              ; cap label var earn_mar          "Average March earnings";
 cap rename remabr               earn_apr              ; cap label var earn_apr          "Average April earnings";
 cap rename remmai               earn_may              ; cap label var earn_may          "Average May earnings";
 cap rename remjun               earn_jun              ; cap label var earn_jun          "Average June earnings";
 cap rename remjul               earn_jul              ; cap label var earn_jul          "Average July earnings";
 cap rename remago               earn_aug              ; cap label var earn_aug          "Average August earnings";
 cap rename remset               earn_sep              ; cap label var earn_sep          "Average September earnings";
 cap rename remout               earn_oct              ; cap label var earn_oct          "Average October earnings";
 cap rename remnov               earn_nov              ; cap label var earn_nov          "Average November earnings";
 cap rename remdezr              earn_dec              ; cap label var earn_dec          "Average December earnings";
 cap rename remdezembro          earn_dec_mw           ; cap label var earn_dec_mw 	 	 "Average December earnings (in min. wages)";
 cap rename remmedr              earn_mean             ; cap label var earn_mean		 "Average earnings";
 cap rename remmedia             earn_mean_mw          ; cap label var earn_mean_mw      "Average earnings (in min. wages)";
 cap rename ultrem				 earn_final			   ; cap label var earn_final        "Last earnings received by worker"; 
 cap rename tipoadm              adm_type              ; cap label var adm_type			 "Admission type";
 cap rename mesadmissa           adm_month             ; cap label var adm_month         "Admission month";
 cap rename dtadmissao           adm_date              ; cap label var adm_date          "Admission date";
 cap rename diadeslig            sep_day               ; cap label var sep_day           "Separation day" ;
 cap rename mesdesli             sep_month             ; cap label var sep_month		 "Separation month";
 cap rename mesdeslig            sep_month             ; cap label var sep_month		 "Separation month";
 cap rename causadesli           sep_cause             ; cap label var sep_cause         "Separation reason";
 cap rename qtdiasafas           days_onleave          ; cap label var days_onleave 	 "Number of days on leave";
 cap rename causafast1           leave_cause1          ; cap label var leave_cause1      "First leave reason";
 cap rename causafast2           leave_cause2          ; cap label var leave_cause2      "Second leave reason";
 cap rename causafast3           leave_cause3          ; cap label var leave_cause3      "Third leave reason";
 cap rename diainiaf1            day_ini_leave1        ; cap label var day_ini_leave1    "Day leave 1 started";
 cap rename diainiaf2            day_ini_leave2        ; cap label var day_ini_leave2    "Day leave 2 started";
 cap rename diainiaf3            day_ini_leave3        ; cap label var day_ini_leave3    "Day leave 3 started";
 cap rename diafimaf1            day_end_leave1        ; cap label var day_end_leave1    "Day leave 1 ended";
 cap rename diafimaf2            day_end_leave2        ; cap label var day_end_leave2    "Day leave 2 ended";
 cap rename diafimaf3            day_end_leave3        ; cap label var day_end_leave3    "Day leave 3 ended";
 cap rename mesiniaf1            mth_ini_leave1        ; cap label var mth_ini_leave1    "Month leave 1 started"; 
 cap rename mesiniaf2            mth_ini_leave2        ; cap label var mth_ini_leave2    "Month leave 2 started";
 cap rename mesiniaf3            mth_ini_leave3        ; cap label var mth_ini_leave3    "Month leave 3 started";
 cap rename mesfimaf1            mth_end_leave1        ; cap label var mth_end_leave1    "Month leave 1 ended";
 cap rename mesfimaf2            mth_end_leave2        ; cap label var mth_end_leave2    "Month leave 2 ended";
 cap rename mesfimaf3            mth_end_leave3        ; cap label var mth_end_leave3    "Month leave 3 ended";
 cap rename trabalhou_mes1       worked_jan            ; cap label var worked_jan 		 "=1 if worked during January";        
 cap rename trabalhou_mes2       worked_feb            ; cap label var worked_feb 		 "=1 if worked during February";
 cap rename trabalhou_mes3       worked_mar            ; cap label var worked_mar 		 "=1 if worked during March";
 cap rename trabalhou_mes4       worked_apr            ; cap label var worked_apr 		 "=1 if worked during April";
 cap rename trabalhou_mes5       worked_may            ; cap label var worked_may 		 "=1 if worked during May";
 cap rename trabalhou_mes6       worked_jun            ; cap label var worked_jun 		 "=1 if worked during June";
 cap rename trabalhou_mes7       worked_jul            ; cap label var worked_jul 		 "=1 if worked during July";
 cap rename trabalhou_mes8       worked_aug            ; cap label var worked_aug 		 "=1 if worked during August";
 cap rename trabalhou_mes9       worked_sep            ; cap label var worked_sep 		 "=1 if worked during September";
 cap rename trabalhou_mes10      worked_oct            ; cap label var worked_oct 		 "=1 if worked during October";
 cap rename trabalhou_mes11      worked_nov            ; cap label var worked_nov 		 "=1 if worked during November";
 cap rename trabalhou_mes12      worked_dec            ; cap label var worked_dec 		 "=1 if worked during December";
 cap rename trabalhou_2016       worked_2016           ; cap label var worked_2016 		 "=1 if worked during 2016";
 cap rename identifica           firmid                ; cap label var firmid            "Firm CNPJ or CEI";
 cap rename tipoestbl            firmid_type           ; cap label var firmid_type       "Firm id type";
 cap rename indceivinc           has_cei               ; cap label var has_cei           "=1 if firm id is CEI";
 cap rename razaosocia           firm_name             ; cap label var firm_name	 	 "Firm name";
 cap rename clascnae20           cnae20                ; cap label var cnae20            "Industry code 2006 classification";
 cap rename sbclas20             cnae20_sub            ; cap label var cnae20_sub        "Industry code 2006 classification subclass";
 cap rename clascnae95           cnae95                ; cap label var cnae95            "Industry code 1995 classification";
 cap rename ibgeativid           industry              ; cap label var industry          "Firm industry";
 cap rename ibgesubset           sector                ; cap label var sector            "Sector";
 cap rename indpat               enrol_pat             ; cap label var enrol_pat 		 "=1 if firm belongs to PAT";
 cap rename indsimples           enrol_simples         ; cap label var enrol_simples     "=1 if firm is enroled in SIMPLES";
 cap rename municipio            muni                  ; cap label var muni				 "Municipality";
 cap rename uf				     state				   ; cap label var state 			 "State (uf)";
 cap rename natjuridic           legal_nature          ; cap label var legal_nature      "Legal nature";
 cap rename tamestab             firm_size_group       ; cap label var firm_size_group	 "Firm size (active workers as of 31/12)";
 cap rename ocup2002             cbo02                 ; cap label var cbo02			 "Occupation codes 2002 classification";
 cap rename ocupacao94           cbo94                 ; cap label var cbo94			 "Occupation codes 1994 classification";
 
 cap drop v61; cap drop meses_trab; cap drop dtadmstr; cap drop anoadmissao; cap drop num_pis;

};
